# Generated by Django 4.0.2 on 2022-11-28 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veridicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veridict_number', models.CharField(max_length=20)),
                ('court_name', models.CharField(max_length=100)),
                ('veridict_date', models.DateField(default=datetime.date.today)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(default=None, upload_to='veridicts/')),
            ],
        ),
    ]
