# Generated by Django 4.0.2 on 2022-02-22 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veridicts', '0002_veridict_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='veridict',
            name='pdf_file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='veridict',
            name='veridict_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
