# Generated by Django 4.0.2 on 2022-06-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veridicts', '0003_veridict_pdf_file_veridict_veridict_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veridict',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='veridicts/'),
        ),
    ]
