# Generated by Django 4.0.2 on 2022-11-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veridicts', '0004_alter_veridict_pdf_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veridict',
            new_name='Veridicts',
        ),
    ]
